name: Auto Update IPTV M3U

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:  # 支持手动触发
    inputs:
      run: 
        description: 'Trigger the M3U update manually'
        required: false
        default: 'yes'

jobs:
  update_m3u:
    runs-on: ubuntu-latest
    env:  # 这里引用 GitHub Secrets
      SOURCE_URL_IPV6_1: ${{ secrets.SOURCE_URL_IPV6_1 }}
      SOURCE_URL_IPV6_2: ${{ secrets.SOURCE_URL_IPV6_2 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 可以根据需要修改 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run M3U Merge Script
        run: |
          python merge_channels.py  # 确保这里的文件名和实际脚本文件名一致

      - name: Commit and push the changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'github-actions@github.com'
          message: 'Auto-update M3U channels list'
